
# dataset info
dataset_name: "underwater_type5_mse"
dataset_path: "/home/scsc/data/underwater_dataset/UWGAN/restoration/Paired/underwater_type4"

# image info
chans: 3
im_width: 256
im_height: 256

# other params
val_interval: 1000 # steps
ckpt_interval: 20  # epochs
 
